Email
Nick9500/ministocks pull request #30
Opened 2018-03-02 01:41 UTC by githubRaj

Addition of export of data(csv) file functionality through email.

2018-03-02 15:17 UTC, Nick9500 commented
Why did you close this? It didn't work?

2018-03-02 19:15 UTC, githubRaj commented
It seems one of the tests is failing

2018-03-02 20:39 UTC, Nick9500 commented on src/main/java/nitezh/ministock/activities/PreferencesActivity.java
> +        String[] toAddress = {"raj34@live.ca"};
Don't hardcode your personal email address in the code, please. Everyone who clicks email will send you their portfolio.

2018-03-02 20:39 UTC, Nick9500 requested changes
Overall good but make the change before merging.

2018-03-04 01:38 UTC, Nick9500 approved these changes
Much better!

2018-03-04 01:41 UTC, merged