Addition of 2 Extra Graph Types
Nick9500/ministocks pull request #64
Opened 2018-04-03 21:23 UTC by everlybolivar

In accordance to Issue #61, a graphical view of a stock can now be shown in another two different graph types (RSI and MACD).

2018-04-05 00:28 UTC, Nick9500 requested changes

2018-04-05 00:28 UTC, Nick9500 commented on src/main/java/nitezh/ministock/activities/ChartActivity.java
> +        /* else if (interval == 5) {
Remove comments please

2018-04-05 00:47 UTC, everlybolivar commented on src/main/java/nitezh/ministock/activities/ChartActivity.java
> +        /* else if (interval == 5) {
Done

2018-04-10 21:41 UTC, Nick9500 approved these changes

2018-04-10 21:42 UTC, merged