Save File On to Device And File Content Test
Nick9500/ministocks pull request #78
Opened 2018-04-13 05:19 UTC by githubRaj

New Feature Added that allows user to either export a file to their device or to their email. The ReadFromFileSent test checks if the data is properly exported through a file, by comparing the contents of the file with the data in the widget row before the export. Addresses Issue: #75.

2018-04-13 18:42 UTC, GurkomalSRao requested changes

2018-04-13 18:42 UTC, GurkomalSRao commented on src/main/java/nitezh/ministock/SaveFile.java
> +            FileOutputStream fOut = new FileOutputStream(fileSavedOnDevice);
variable newFile is never used

2018-04-13 18:42 UTC, GurkomalSRao commented on src/main/java/nitezh/ministock/activities/PreferencesActivity.java
> +import nitezh.ministock.Storage;
`import nitezh.ministock.Storage;` never used

2018-04-13 19:15 UTC, GurkomalSRao requested changes

2018-04-13 19:15 UTC, GurkomalSRao commented on src/test/java/nitezh/ministock/activities/EmailTest.java
> +
in email test you have password hard coded. should be changed

2018-04-14 02:48 UTC, GurkomalSRao approved these changes

2018-04-14 02:49 UTC, Nick9500 approved these changes

2018-04-14 02:49 UTC, merged